### ISSUE TITLE
使用vagrantfile创建虚拟机出错

### ISSUE THREAD

**Issue by wuShanMulan** [baijunyao/laravel-bjyadmin#1]
白俊遥，您好！
使用您本项目提供的vagrantfile创建虚拟机时，出现如下错误信息
 LoadError: cannot load such file --***/vendor/laravel/homestead/scripts/homestead.rb
我也在项目中寻找homestead.rb文件，但未找到。烦请解答，谢谢！

**Comment by baijunyao** [comment]
您好：
您需要先在项目中  composer install ；
homestead.rb 的目录为：/vendor/laravel/homestead/scripts/homestead.rb
不过；暂时不建议使用此项目用于开发；现在还处于测试调整阶段；经常会有大的变动；
等逐步完善稳定后；我会写一系列的教程来讲解；

**Comment by wuShanMulan** [comment]
好的，谢谢！

**Comment by baijunyao** [comment]
不客气；
